name: recharge
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.10.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  auto_route: ^10.1.2
  json_annotation: ^4.9.0
  retrofit: ^4.7.2
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0

  # NETWORK

  # CORE

  # LOGGING
  talker: ^5.0.1
  talker_flutter: ^5.0.1
  talker_dio_logger: ^5.0.1
  talker_bloc_logger: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4
  retrofit_generator: ^9.7.0
  json_serializable: ^6.9.5


flutter:
  uses-material-design: true
  assets:
    - .env
  
